### ISSUE TITLE
Future. 

### ISSUE THREAD

**Issue by simonv3** [opensourcedesign/job-board#1]
What's the plan here? Just a single file for now? 

I'm actually working on a little application that I would love to make OSS that fits into this category.

**Comment by yoroy** [comment]
Why not start with using these github issues to create a simple forum of some kind. See https://github.com/opensourcedesigners/job-board/issues/2 for example. 

I'd be reluctant to create a new thing for this, more interested in somehow aggregating what's already there and make design specific issues better discoverable.

**Comment by simonv3** [comment]
@yoroy For sure. You'll notice that the issue was raised almost 8 months ago. There's a lot of "job boards" already out there, and they're not the best way to actually get some work, and a lot more have cropped up over the past few months. A job board doesn't really make sense.

On the other hand, I'm reluctant to just make it a "here's an OSS project that needs your help to design things." I think there's a big misconception that people work on OSS as volunteers rather than as paid work, and I would rather not see this become a mantle for "do free work". That's something the design community already suffers from.
