### ISSUE TITLE
LNUG Stickers

### ISSUE THREAD

**Issue by iancrowther** [opensourcedesign/job-board#2]
Hi All,

I'm a dev!  Im looking for some hexagon stickers for our OSS meetup.  

It's all non-profit and help is defo wanted

https://github.com/lnug

Thanks

**Comment by sohlis** [comment]
What are you looking for exactly? Are you just looking for [solid sticker vendors](https://www.stickermule.com/)?

**Comment by iancrowther** [comment]
Designers more so

**Comment by bnvk** [comment]
@iancrowther yah, best thing to do is create a "job" in this repo. Do the following:

- Fork the repo
- Copy `job-template.md` into the `jobs` folder
- Name your compy something like `2015-03-sticker-design-for-lnug.md`
- Fill out the fields inside the template you just copied
- Submit a pull request
- Have a margarita

After those steps you will have submitted a job to the OSD job board ;)

**Comment by iancrowther** [comment]
great thanks for this

**Comment by evalica** [comment]
FTR: I don't think a PR has been created for this request.
