### ISSUE TITLE
Should it be Projects or Jobs?

### ISSUE THREAD

**Issue by bnvk** [opensourcedesign/job-board#5]
@pfefferle agreed. Perhaps we should rename "job-board" to "projects" ? To me "jobs" implies money and budgets... where as "projects" could be a paying project, or a for gratis project.

**Comment by pfefferle** [comment]
That is also a good point... I prefer projects!

But this was not my intention... I thought about a repo that represents this project/community (@opensourcedesign) to collect issues like:

* we need a logo
* we need a webpage
*...

**Comment by paulproteus** [comment]
You could call that repo "meta"., to avoid confusion with "projects" that
are what goes on the "projects board", or "group-planning" or
"group-identity" but I would call it "meta" if I were you!

**Comment by simonv3** [comment]
:+1: to meta

**Comment by skddc** [comment]
Job means money, yes. I thought that's what it was however, and I liked the idea.

**Comment by simonv3** [comment]
@skddc I semi-agree, like I pointed out [here](https://github.com/opensourcedesign/job-board/issues/1#issuecomment-72978684):

> I would rather not see this become a mantle for "do free work". That's something the design community already suffers from.

But projects is probably just a better descriptor of the goal of the this?

**Comment by skddc** [comment]
I'm not sure I understand. I meant to say that I like the idea of people doing open source work (design or not) and getting paid for it. I think there should be more actual open source jobs, because people need to pay rent and put food on the table, and doing it while working 100% on open source is just so much nicer than sharing time between mostly "normal" work and a little bit of open source on the side.

**Comment by simonv3** [comment]
@skddc I'm saying I agree with the paid aspect - I would prefer that this became a venue for finding paid work on open source projects, or commons driven projects, rather than going down the path of becoming a place where organizations or group post work that they need done and hope to get it done for free. I don't think that's a healthy environment, and wouldn't nourish designers and wouldn't be sustainable.

But the term project is more flexible I think - project work is popular, not just within the OSS environment. It's a much more flexible term than "job".

Project can also be a descriptor of OSS, so for example, Mailpile is a project. Hoodie is a project. And often these projects need little tidbits (design or otherwise) fixed rather than a dedicated job.

So that's what I meant with "projects is a better descriptor". It just seems to apply to more things.

**Comment by skddc** [comment]
I agree. Except I think we need both more paid und more unpaid designers in open source projects and that people should be able to hope to find volunteers here as well.

**Comment by GarthDB** [comment]
It really really needs a logo. The [open source initiative logo guidelines](http://opensource.org/logo-usage-guidelines#Complementary_Font) outline usage, and I don't think this project falls within those guidelines.

**Comment by una** [comment]
PROJECTS. Much less intimidating. And job can be interpreted as "well.. I already have a job... so this isn't for me'

**Comment by bnvk** [comment]
Very interesting dialogue everyone, thanks for chiming in and exploring this "naming" issue with me. What I'm thinking after reading all of your careful thoughts is that we should have a repo called [Projects](https://github.com/opensourcedesign/projects), a repo called [People](https://github.com/opensourcedesign/people), and that we keep this "**Job Board**" repo yet maybe shorten it to just "**Jobs**". 

Here is the overall thinking that @jancborchardt and I are thinking for how we grow this site & effort:

**People**
A collection of people who work on various FOSS projects as either designers or other roles

**Projects**
A collection of OS + design focused projects that "people" have worked on in the past, projects we're currently working, or new potential projects

**Jobs**
A job board will be just that, where "People" post jobs about "Projects" which may be paying or gratis. The reasoning we have for this whole OSD effort is shifting the perception and locus away from:

```
 Oh, open source means work on badly designed / confusing apps for free!
```

And shifting things more towards something like:

```
Open source means working on sustainable awesome projects that help humanity, and yes it can be a paying full time job or a fun hobby you do in spare moments!
```

As @jancborchardt said: "I think it's good to not shy away from money-related stuff there" and also "that we can also relay job ads from Moz and Canonical regarding design"

I think it will be ok and not slip into just paying work as long as we properly communicate that anyone can submit "jobs" even if they don't pay.

I'm going to close this issue, unless any of you feel "blocking" about this name change / developments :smile:

**Comment by una** [comment]
People: exists here: http://designopensrc.com/index.html#/
Job/Project Board: is being created already here: https://github.com/DesignOpen/board

Synthesis > fragmentation y'all :)

**Comment by bnvk** [comment]
@una ah, that they do... I remember coming across the "people" page at one point last week, I connected my GH account... but it's not linked to / mentioned on [designopen.org](http://designopen.org) site so I kinda forgot.

Both those repos seem to be RubyonRails apps. Dang. I was hoping to create this site ontop of simple GH pages + Markdown files, but I agree "synthesis > fragmentation" and I forsee this sorta thing  happening again and again if we have 2 different sites + 2 diff GH orgs...

Another reason to merge it all? :smile: what do you think @GarthDB ?

**Comment by skddc** [comment]
Yer, it's easier to manage in one repo, if it belongs to one website/domain.

**Comment by una** [comment]
The job/project board is a separate project from Design Open (which is the organization containing a website for resources/ blog posts/ an entry point for designers to practice open source design within as well as several other projects). 

The job board is an additional initiative under its umbrella :) 

Since we all have the same end goals, rather than starting something new and separate, we should all just get more eyes on the existing initiatives :)

**Comment by una** [comment]
Also, yes it should be linked in the Resources under the Design-Open Site. Good call @bnvk

**Comment by jancborchardt** [comment]
So why isn’t the blogs of designopen just opensourcedesign.net/blog?

> The job board is an additional initiative under its umbrella :)

Why that? Doesn’t need to be separate. I’d say we can put it as opensourcedesign.net/jobs?

**Comment by bnvk** [comment]
@una nice, on adding the link. I agree 100% not starting something new and separate is the goal- I think @jancborchardt, myself and others all agree on that. We've suggested a few times this week merging "all the things" :stuck_out_tongue_closed_eyes:  but i'm not sure the status / feelings from @opendesign GH org owners like @GarthDB et. al. 

I just filed [this issue](https://github.com/opensourcedesign/opensourcedesign.github.io/issues/1) to better outline my thinking!

**Comment by GarthDB** [comment]
I'm on the road. I'll write a more descriptive response tomorrow.



—

**Comment by GarthDB** [comment]
@bnvk I'm not against merging things that make sense, but DesignOpen is starting to get a pretty solid foundation based on some key points, so wherever we actually are working toward the same goals, we should merge our efforts.

Our primary goal is to improve the overall design standards in open source projects, while a close secondary goal is to help designers understand and take advantage of benefits of open source practices 

This secondary goal includes open source, but is not limited to projects with open source licenses. We encourage designers to also be more open about their non-open source projects and to find opportunities to collaborate with developers and other designers.

Also, as part of the primary goal we are making efforts to education developers on basic design principles - it seems right now that the most active designers in open source projects are often hybrid designer/developers, so if we can help create more of those, we should have more design activity in open source projects.

Finally, to help both designers and developers collaborate better, we are working on tools where we have resources. The first is the Design Open Project Board (see the [prototype](http://designopen.org/Prototyped/board/)).  For the first version we have nothing planned for paid projects, it is solely for the purpose giving open source projects a place to post requests for design help. We aren't against paid open source design gigs, but for right now at least, that's not the goal.

The second tool we're working on is a resource collector bookmarlet (and maybe chrome extension). This is just a tool to help us (and anyone in the community) collect open source design resources we come across, put them in github issues, and then curate and post on the designopen.org website.

If you would like to merge efforts on any of these fronts, we'd love to have the help, but we aren't looking to change our goals right now. Let me know what you'd like to do.
